### ISSUE TITLE
calmjs.indexer.modgen is incompatible with _frozen_importlib_external._NamespacePath

### ISSUE THREAD

**Issue by metatoaster** [calmjs/calmjs#29]
Following symptom will appear:

```
>>> import calmjs.indexer
>>> import calmjs
>>> list(calmjs.indexer.modgen(calmjs))
Traceback (most recent call last):
  File "/tmp/.env35/lib/python3.5/site-packages/calmjs/indexer.py", line 129, in modgen
    module_base_paths = modpath_f(module, entry_point)
  File "/tmp/.env35/lib/python3.5/site-packages/calmjs/indexer.py", line 201, in modpath_last
    return module_paths[-1:]
TypeError: '_NamespacePath' object is not subscriptable
```

**Comment by metatoaster** [comment]
Not actually related to modgen at all, the fault complete lies with the deprecated modpath_last method which creates the broken behavior.  As the usage of this function will be completely deprecated soon, this is being closed.
