### ISSUE TITLE
3.4.3: 7 failing tests 

### ISSUE THREAD

**Issue by dvzrv** [calmjs/calmjs#66]
Hi! When trying to package 3.4.3 for Arch Linux I ran into issues running the tests. I finally got them to run, but there are still seven failing tests.

I'm running things like this:

```
python·-m·build·--wheel·--no-isolation
local·site_packages=$(python·-c·"import·site;·print(site.getsitepackages()[0])")
python·-m·installer·--destdir=test_dir·dist/*.whl
export·PYTHONPATH="$PWD/test_dir/$site_packages:$PYTHONPATH"
python·-m·unittest·discover·-vs·src/$_name/tests/
```

This leads to:
```

======================================================================
FAIL: test_logging_all (test_command.DistLoggerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_command.py", line 51, in test_logging_all
    self.assertEqual(sys.stdout.getvalue(), 'Information\nDebug\n')
AssertionError: '' != 'Information\nDebug\n'
+ Information
+ Debug


======================================================================
FAIL: test_logging_bad (test_command.DistLoggerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_command.py", line 37, in test_logging_bad
    self.assertTrue(sys.stderr.getvalue().startswith(
AssertionError: False is not true

======================================================================
FAIL: test_logging_info_only (test_command.DistLoggerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_command.py", line 60, in test_logging_info_only
    self.assertEqual(sys.stdout.getvalue(), 'Information\n')
AssertionError: '' != 'Information\n'
+ Information


======================================================================
FAIL: test_init_no_overwrite_default_input_interactive (test_npm.DistCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_npm.py", line 723, in test_init_no_overwrite_default_input_interactive
    self.assertTrue(stdout.startswith("running npm\n"))
AssertionError: False is not true

======================================================================
FAIL: test_init_overwrite (test_npm.DistCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_npm.py", line 772, in test_init_overwrite
    self.assertIn("wrote '%s'\n" % join(tmpdir, 'package.json'), stdout)
AssertionError: "wrote '/tmp/tmpqm13a13a/package.json'\n" not found in ''

======================================================================
FAIL: test_init_no_overwrite_default_input_interactive (test_yarn.DistCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_yarn.py", line 643, in test_init_no_overwrite_default_input_interactive
    self.assertTrue(stdout.startswith("running yarn\n"))
AssertionError: False is not true

======================================================================
FAIL: test_init_overwrite (test_yarn.DistCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-calmjs/src/calmjs-3.4.3/src/calmjs/tests/test_yarn.py", line 692, in test_init_overwrite
    self.assertIn("wrote '%s'\n" % join(tmpdir, 'package.json'), stdout)
AssertionError: "wrote '/tmp/tmpxco3pn62/package.json'\n" not found in ''

----------------------------------------------------------------------
Ran 668 tests in 2.617s

FAILED (failures=7)
```

[python-calmjs-3.4.3-1-x86_64-build.log](https://github.com/calmjs/calmjs/files/10875457/python-calmjs-3.4.3-1-x86_64-build.log)
[python-calmjs-3.4.3-1-x86_64-check.log](https://github.com/calmjs/calmjs/files/10875458/python-calmjs-3.4.3-1-x86_64-check.log)

As I couldn't get the tests to run using pytest at all, I'm sort of stuck with unittest and that doesn't allow me to disable/ignore tests on the commandline (at least I could not figure out how to do that - with pytest it is very easy).

I guess I could remove the fiels with the offending tests, but to me some of the issues look like they may be depending on specific versions of yarn and or npm.
We currently ship yarn 1.22.19 and npm 8.19.2 (both are available in PATH).

**Comment by metatoaster** [comment]
These failures are ones I've seen before on appveyor tests on Windows but I wasn't able to replicate the conditions that cause the `sys.stdout` to fail to be captured using the method I used - all of them are related to integration with `distutils` (well, `setuptools` going forward) and should have nothing to do with the real `yarn` or `npm` as the ones being executed by these tests are synthetic binaries.

Perhaps I will also need to change how logging is being captured, or figure out exactly how capturing fails.

**Comment by metatoaster** [comment]
This is actually caused by the latest versions of `setuptools`, where it has begun to shadow the Python standard library module `distutils` and its related submodule, the changed handling causes conflicts with the test cases.

A workaround will be provided at some point.

**Comment by metatoaster** [comment]
`calmjs-3.4.4` should address this issue by removing the test cases that will definitely be incompatible with Python 3.12, though I am not sure how ``setuptools`` will maintain that ``distutils`` namespace so I am in a bit of a bind too.
